# Site settings
title: RIA TREPPO
email: riatreppo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ria Treppo, Architektur + Tapisserie in Breitenbrunn & Purbach, Eisenstadt-Umgebung, Burgenland
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://riatreppo.com" # the base hostname & protocol for your site
image_folder: "images"

# Build settings
markdown: kramdown
